CREATE DATABASE IF NOT EXISTS todo;

USE todo;

CREATE TABLE IF NOT EXISTS todo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NULL,
    description VARCHAR(500) NULL,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP
);
